pipeline {
    agent { label 'AGENT-1' }

    environment {
        PROJECT = 'expense'
        COMPONENT = 'backend'
        appVersion = ''
        ACC_ID = '178173414156'

    }
    options { disableConcurrentBuilds() 
              timeout(time: 30, unit: 'MINUTES')
              ansiColor('xterm')
    }
/*     parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }  */

    stages {
            stage('Init'){
                steps{
                    script{
                       withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                            
                           sh """
                            cd 00-vpc
                            terraform init -reconfigure
                            terraform plan

                            """
                        }
                    }
                }
            }

            stage('Apply'){
                input {
                        message "Should we continue?"
                        ok "Yes, we should."
                        
                }
                steps{
                    script{
                       withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                            
                           sh """
                            cd 00-vpc
                            terraform apply -auto-approve

                            """
                        }
                    }
                }
            }

    }
    post { 
            always { 
             echo 'I will always say Hello again!'
             deleteDir()
        }
            failure { 
             echo 'I will run when pipeline failed'
        }
            success { 
             echo 'I will run when pipeline success'
        }
    }
}